/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/context/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Chloe Showroom ──
        'onyx-black':               '#0A0A0A',
        'platinum-grey':            '#E5E5E5',
        'primary':                  '#000000',
        'on-primary':               '#ffffff',
        'surface':                  '#f9f9f9',
        'on-surface':               '#1a1c1c',
        'on-surface-variant':       '#4c4546',
        'surface-container':        '#eeeeee',
        'surface-container-low':    '#f3f3f4',
        'surface-container-lowest': '#ffffff',
        'surface-dim':              '#dadada',
        'surface-variant':          '#e2e2e2',
        'outline':                  '#7e7576',
        'outline-variant':          '#cfc4c5',
        'secondary':                '#795741',
        'secondary-container':      '#fed1b5',
        'on-secondary-container':   '#795842',
        'tertiary':                 '#000000',
        'tertiary-fixed':           '#e8e2d4',
        'tertiary-container':       '#1d1c13',
        'on-tertiary-container':    '#888478',
        'inverse-surface':          '#2f3131',
        'inverse-on-surface':       '#f0f1f1',
        'inverse-primary':          '#c6c6c6',
        'primary-container':        '#1b1b1b',
        'on-primary-container':     '#848484',
        'primary-fixed':            '#e2e2e2',
        'primary-fixed-dim':        '#c6c6c6',
        'error':                    '#ba1a1a',
      },
      fontFamily: {
        'body-md':             ['var(--font-karla)', 'Karla', 'sans-serif'],
        'body-lg':             ['var(--font-karla)', 'Karla', 'sans-serif'],
        'caption':             ['var(--font-karla)', 'Karla', 'sans-serif'],
        'label-md':            ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'headline-lg':         ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'headline-lg-mobile':  ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
        'display-lg':          ['var(--font-hanken)', 'Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'caption':            ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-md':           ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg':        ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        'display-lg':         ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '300' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      spacing: {
        'gutter':          '24px',
        'margin-mobile':   '20px',
        'margin-desktop':  '64px',
        'section-gap':     '120px',
      },
    },
  },
  plugins: [],
};